name: Node.js pnpm install action
description: |
  Composite action to setup Node.js and pnpm versions according to 'NODE_VERSION'
  and 'PNPM_VERSION' environment variables. As well as installing dependencies.

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: ${{ env.PNPM_VERSION }}
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: "pnpm"
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --ignore-scripts
