name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  NODE_VERSION: 20.13
  PNPM_VERSION: 9.1.2
  DO_NOT_TRACK: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-pnpm-setup
      - name: Lint
        run: |
          pnpm lint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-pnpm-setup
      - name: Prettier
        run: |
          pnpm install --frozen-lockfile
          pnpm prettier:check

  build:
    needs: [lint, prettier]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-pnpm-setup
      - name: Build
        run: |
          pnpm install --frozen-lockfile
          pnpm build
