name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  NODE_VERSION: 20.14
  PNPM_VERSION: 9.4.0
  DO_NOT_TRACK: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-pnpm-install
      - name: Lint
        run: pnpm lint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-pnpm-install
      - name: Prettier
        run: pnpm prettier:check

  build-ditto:
    needs: [lint, prettier]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build (ditto)
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: docker build . --target ditto --tag ditto:$IMAGE_TAG
